<?php

const ESTUDIANTE = "ESTUDIANTE";
const EST_ID = "EST_ID";
const EST_NOMBRE = "EST_NOMBRE";
const EST_DEPORTE = "EST_DEPORTE";
const EST_COLOR = "EST_COLOR";
const EST_MODIFICACION = "EST_MODIFICACION";
const EST_ELIMINADO = "EST_ELIMINADO";
